### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Fachher** [totalamateurhour/oracle-12.2-vagrant#3]
System information
- Mac OS 
- Virtualbox (5.1.30 r118389) 
- Vagrant (2.0.0) 
- Oracle VM VirtualBox Extension Pack (5.1.30r118389) 

I have downloaded http://download.oracle.com/otn/linux/oracle12c/122010/linuxx64_12201_database.zip

```
==> default: /tmp/vagrant-shell: line 42: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
==> default: /tmp/vagrant-shell: line 43: /opt/oracle/product/12.2.0.1/dbhome_1/root.sh: No such file or directory
==> default: INSTALLER: Oracle software installed
==> default: -bash: netca: command not found
==> default: INSTALLER: Listener created
==> default: -bash: dbca: command not found
==> default: -bash: sqlplus: command not found
==> default: INSTALLER: Database created
==> default: sed: can't read /etc/oratab: No such file or directory
==> default: INSTALLER: Oratab configured
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/oracle-rdbms.service to /etc/systemd/system/oracle-rdbms.service.
==> default: Job for oracle-rdbms.service failed because the control process exited with error code. See "systemctl status oracle-rdbms.service" and "journalctl -xe" for details.
==> default: INSTALLER: Created and enabled oracle-rdbms systemd's service
==> default: INSTALLER: Installation complete, database ready to use!
```

**Comment by totalamateurhour** [comment]
Is the error on line 42 the first one you see? Can you post more of the output? Is it possible your host ran out of space for the virtual disk?

**Comment by Fachher** [comment]
Yes, line 42 is the first error I see and I think I have enough harddisk space left. 

$ df -h
Filesystem                           Size   Used  Avail Capacity   iused    ifree %iused  Mounted on
/dev/disk1                          233Gi  200Gi   32Gi    87%  52569575  8409239   86%   /

mentioned programs are not included inside of /linuxx64_12201_database.zip
- netca
- dbca
- sqlplus

**Comment by totalamateurhour** [comment]
My guess is that it's rather something with a PATH environment variable.  After this error, can you do the following:

vagrant ssh
ls /opt/oracle/product/12.2.0.1/dbhome_1/bin/netca

**Comment by Fachher** [comment]
Hi @totalamateurhour retried it today on my private computer.

Mac OS
Virtualbox 5.1.26 r117224
Vagrant 1.9.0

Everything works out of the box

**Comment by totalamateurhour** [comment]
hi @Fachher - glad you got it working. For what it's worth, I'm not seeing any issues with vbox 5.1.30 and Vagrant 2.0.0.  I just reran this:

$ vboxmanage -v
5.1.30r118389
$ vagrant -v
Vagrant 2.0.0
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'http://yum.oracle.com/boxes/oraclelinux/ol73/ol73.box'...
==> default: Matching MAC address for NAT networking...

...

==> default: Executing Post Configuration Actions
==> default: 100% complete
==> default: Look at the log file "/opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log" for further details.
==> default: 
==> default: SQL*Plus: Release 12.2.0.1.0 Production on Tue Oct 31 19:35:19 2017
==> default: 
==> default: Copyright (c) 1982, 2016, Oracle.  All rights reserved.
==> default: 
==> default: Connected to:
==> default: Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
==> default: SQL> 
==> default: Pluggable database altered.
==> default: 
==> default: SQL> 
==> default: Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
==> default: INSTALLER: Database created
==> default: INSTALLER: Oratab configured
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/oracle-rdbms.service to /etc/systemd/system/oracle-rdbms.service.
==> default: INSTALLER: Created and enabled oracle-rdbms systemd's service
==> default: INSTALLER: Installation complete, database ready to use!
$
